apps/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.utils import text
from plugins import pool

from . import views

urlpatterns = [
    path("a/", include("entry.urls")),
    path("a/", include("post.urls", namespace="post")),
    path("a/", include("files.admin_urls")),
    path("a/", include("trips.urls")),
    path("a/", include("plugins.urls")),
    path("a/wordpress/", include("wordpress.urls", namespace="wordpress")),
    path("a/", include("indieweb.urls", namespace="indieweb")),
    path("files/", include("files.urls")),
    path("", include("feeds.urls", namespace="feeds")),
    path("webmention/", include("webmention.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("favicon.ico", views.favicon),
]

# Include any plugin urls after core urls.
plugin_urls = [path("", include(plugin_urls)) for plugin_urls in pool.plugin_pool.urls()]
urlpatterns.extend(plugin_urls)

plugin_admin_urls = [
    path(f"a/plugins/{text.slugify(plugin.name)}/", include(plugin.admin_urls))
    for plugin in pool.plugin_pool.enabled_plugins()
    if plugin.admin_urls
]
urlpatterns.extend(plugin_admin_urls)

# Public urls are last so "slug-like" urls in plugins are not matched to the stream-list view.
urlpatterns.append(
    path("", include("public.urls", namespace="public")),
)


handler404 = views.handle404

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

apps/feeds/urls.py
from django.urls import path

from . import views

app_name = "feeds"

urlpatterns = [
    path("feed/", views.AllEntriesFeed(), name="feed"),
    path("<slug:stream_slug>/feed/", views.StreamFeed(), name="stream_feed"),
]

apps/plugins/urls.py
from django.urls import path, re_path

from . import views

app_name = "plugins"

urlpatterns = [
    path("plugins/", views.plugin_list, name="plugin_list"),
    re_path(r"^plugins/(?P<identifier>[a-z.]+)/enable/$", views.enable_plugin, name="plugin_enable"),
    re_path(r"^plugins/(?P<identifier>[a-z.]+)/disable/$", views.disable_plugin, name="plugin_disable"),
]

apps/post/urls.py
from django.urls import path

from . import views

app_name = "post"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
]

apps/trips/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("trips/", views.TripListView.as_view(), name="trips"),
    path("trips/create/", views.CreateTripView.as_view(), name="trip_create"),
    path("trips/<int:pk>/edit/", views.UpdateTripView.as_view(), name="trip_edit"),
    path("trips/<int:pk>/delete/", views.DeleteTripView.as_view(), name="trip_delete"),
]

apps/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block meta %}{% endblock %}
    <link href="{% static 'tailwind/style.css' %}" rel="stylesheet">
    <link href="{% static 'trix/trix.css' %}" rel="stylesheet">
    <link href="{% static 'leaflet/leaflet.css' %}" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet-geosearch@3.0.0/dist/geosearch.css"
    />
    {% with request.scheme|add:"://"|add:request.get_host as absolute_url %}
        <link href="{{ absolute_url }}{% url  'indieweb:indieauth_authorize' %}" rel="authorization_endpoint">
        <link href="{{ absolute_url }}{% url  'indieweb:indieauth_token' %}" rel="token_endpoint">
    {% endwith %}
    {% if form %}{{ form.media.css }}{% endif %}
    <title>{{ page_title }} – {{ request.settings.title }} Admin</title>
    <script src="{% static 'trix/trix.js' %}"></script>
    <script src="{% static 'trix/attachments.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
</head>
<body class="bg-bianca-500">
    <div class="">
        <header class="max-w mx-auto p-2">
             <nav  data-controller="reveal">
                <div class="flex">
                    <h1 class="text-negroni-900 text-2xl">
                        <a href="{% url "public:home" %}">
                            {% if request.settings.icon %}
                                <span class="mr-1">{{ request.settings.icon }}</span>
                            {% endif %}{{ request.settings.title }} Admin
                        </a>
                    </h1>
                    <div class="ml-auto pt-2 md:hidden">
                        <button data-reveal-target="button" data-action="click->reveal#toggle">
                            <div class="w-8 bg-negroni-700 h-1"></div>
                            <div class="w-8 bg-negroni-700 h-1 mt-1"></div>
                            <div class="w-8 bg-negroni-700 h-1 mt-1"></div>
                        </button>
                    </div>
                </div>
                <ul data-reveal-target="item" class="mb-2 hidden md:hidden mt-2">
                    <li class="{% if nav == 'dashboard' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "post:dashboard" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">🏡</span><span>Home</span></a></li>
                    <li class="{% if nav == 'posts' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "posts" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">✏️</span><span>Posts</span></a></li>
                    <li class="{% if nav == 'trips' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "trips" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">✈️️</span><span>Trips</span></a></li>
                    <li class="{% if nav == 'files' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "files" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">🗄️</span><span>Files</span></a></li>
                    <li class="{% if nav == 'plugins' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "plugins:plugin_list" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">🔌️</span><span>Plugins</span></a></li>

                    <li class="{% if nav == 'settings' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url 'admin:index' %}"><span class="mr-1">⚙️</span><span>Settings</span></a></li>
                </ul>
            </nav>
        </header>
        <div class="md:flex">
            <nav id="section-nav" class="min-w-min p-2 flex flex-col hidden md:block">
                <ul class="mb-2" data-controller="select" data-select-selected-class="selected">
                    <li class="{% if nav == 'dashboard' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "post:dashboard" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">🏡</span><span>Home</span></a></li>
                    <li class="{% if nav == 'posts' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "posts" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">✏️</span><span>Posts</span></a></li>
                    <li class="{% if nav == 'trips' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "trips" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">✈️️</span><span>Trips</span></a></li>
                    <li class="{% if nav == 'files' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "files" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">🗄️</span><span>Files</span></a></li>
                    <li class="{% if nav == 'plugins' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url "plugins:plugin_list" %}" data-turbo-frame="_top" data-action="select#click"><span class="mr-1">🔌️</span><span>Plugins</span></a></li>
                    <li class="{% if nav == 'settings' %}selected{% endif %} w-28 p-1 mb-2" data-select-target="menuItem"><a href="{% url 'admin:index' %}"><span class="mr-1">⚙️</span><span>Settings</span></a></li>
                </ul>
            </nav>
            {% if nav == "dashboard" %}
                <div class="mx-auto mx-2 grid grid-cols-2 gap-2 md:hidden">
                    <a href="{% url "status_create" %}" data-turbo-frame="_top" class="primary-button"><span class="mr-1">💬</span><span class="hover:underline">New Status</span></a>
                    <a href="{% url "article_create" %}" data-turbo-frame="_top" class="primary-button"><span class="mr-1">✏️</span><span class="hover:underline">New Article</span></a>
                    <a href="{% url "reply_create" %}" data-turbo-frame="_top" class="primary-button"><span class="mr-1">📤️</span><span class="hover:underline">New Reply</span></a>
                    <a href="{% url "bookmark_create" %}" data-turbo-frame="_top" class="primary-button"><span class="mr-1">🔖️</span><span class="hover:underline">New Bookmark</span></a>
                </div>
            {% endif %}
            <div id="content" class="w-11/12 flex flex-col">
                {% block content %}
                {% include "fragments/content.html" %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

apps/templates/base_public.html
{% load static plugins indieweb %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% if title %}{{ title }} - {% endif %}{{ request.settings.title }}</title>
    {% with request.scheme|add:"://"|add:request.get_host as absolute_url %}
    <link rel="alternate" type="application/rss+xml" title="{% if request.settings.icon %}{{ request.settings.icon }} {% endif %}{{ request.settings.title }}" href="{{ absolute_url }}{% url 'feeds:feed' %}">
    {% if stream %}
    <link rel="alternate" type="application/rss+xml" title="{% if request.settings.icon %}{{ request.settings.icon }} {% endif %}{{ request.settings.title }} - {{ stream.name }} Feed" href="{{ absolute_url }}{% url 'feeds:stream_feed' stream.slug %}">
    {% endif %}
    {% render_relme %}
    <link href="{{ absolute_url }}{% url  'indieweb:indieauth_authorize' %}" rel="authorization_endpoint"/>
    <link href="{{ absolute_url }}{% url  'indieweb:indieauth_token' %}" rel="token_endpoint"/>
    <link href="{{ absolute_url }}{% url 'indieweb:micropub' %}" rel="micropub"/>
    <link href="{{ absolute_url }}{% url 'micropub_media' %}" rel="micropub_media"/>
    <link href="{% static "tailwind/style.css" %}" rel="stylesheet"/>
    {% if request.settings.theme %}
        <link href="{% static request.settings.theme|default:"tailwind"|add:"/style.css" %}" rel="stylesheet"/>
    {% endif %}
    <link rel="webmention" href="{{ absolute_url }}{% url "webmention:receive" %}"/>
    {% endwith %}
    <link href="{% static 'leaflet/leaflet.css' %}" rel="stylesheet">
    <script src="{% static 'js/public.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="bg-primary">
    <div class="min-h-screen flex flex-col">
        <header class="p-2">
            {% block header %}
            <nav  data-controller="reveal">
                <div class="flex">
                    <h1 class="text-secondary text-2xl">
                        <a href="{% url "public:home" %}">
                            {% if request.settings.icon %}
                                <span class="mr-1">{{ request.settings.icon }}</span>
                            {% endif %}{{ request.settings.title }}
                        </a>
                    </h1>
                    <a href="{% url "public:trips" %}" class="{% if 'trips' in selected %}border-b-4 border-secondary{% endif %} ml-2 leading-8 hidden md:inline-block"><span class="mr-1">✈️</span><span>Trips</span></a>
                    <a href="{% url "public:cluster_map" %}" class="{% if 'maps' in selected %}border-b-4 border-secondary{% endif %} ml-2 leading-8 hidden md:inline-block"><span class="mr-1">🗺️</span><span>Maps</span></a>

                    {% for plugin in request.plugin_pool.enabled_plugins %}
                        {% if plugin.has_public_top_nav %}
                            {% render_plugin plugin.identifier "NAV.TOP" %}
                        {% endif %}
                    {% endfor %}
                    <div class="ml-auto pt-2 md:hidden">
                        <button data-reveal-target="button" data-action="click->reveal#toggle">
                            <div class="w-8 bg-secondary h-1"></div>
                            <div class="w-8 bg-secondary h-1 mt-1"></div>
                            <div class="w-8 bg-secondary h-1 mt-1"></div>
                        </button>
                    </div>
                </div>
                <ul data-reveal-target="item" class="mb-2 hidden md:hidden mt-2">
                    {% if request.user.is_authenticated %}
                        <li class="p-1 mb-2"><a href="{% url "post:dashboard" %}" class="w-full inline-block"><span class="mr-1">🖥</span><span>Dashboard</span></a></li>
                    {% endif %}
                    <li class="{% if 'home' in selected %}border-l-4 border-secondary{% endif %} p-1 mb-2"><a href="{% url "public:home" %}" class="w-full inline-block"><span class="mr-1">🏡</span><span>Home</span></a></li>
                    <li class="{% if 'trips' in selected %}border-l-4 border-secondary{% endif %} p-1 mb-2"><a href="{% url "public:trips" %}" class="w-full inline-block"><span class="mr-1">✈️</span><span>Trips</span></a></li>
                    <li class="{% if 'maps' in selected %}border-l-4 border-secondary{% endif %} p-1 mb-2"><a href="{% url "public:cluster_map" %}" class="w-full inline-block"><span class="mr-1">🗺️</span><span>Maps</span></a></li>
                    {% for plugin in request.plugin_pool.enabled_plugins %}
                        {% if plugin.has_public_top_nav %}
                            {% render_plugin plugin.identifier "NAV.TOP.MOBILE" %}
                        {% endif %}
                    {% endfor %}
                    {% for stream in streams %}
                        <li class="{% if stream.slug in selected %}border-l-4 border-secondary{% endif %} p-1 mb-2"><a href="{% url "public:stream" stream.slug %}" class="w-full inline-block"><span class="mr-1">{{ stream.icon }}</span><span>{{ stream.name }}</span></a></li>
                    {% endfor %}
                </ul>
            </nav>
            {% endblock %}
        </header>
        <div class="md:flex md:flex-grow">
            {% block content_wrapper  %}
                {% block stream_nav %}
                    <nav id="section-nav" class="min-w-min p-2 flex flex-col hidden md:block">
                        <ul class="mb-2">
                            {% if request.user.is_authenticated %}
                                <li class="p-1 mb-2"><a href="{% url "post:dashboard" %}" class=" w-36 p-1 mb-2"><span class="mr-1">🖥</span><span>Dashboard</span></a></li>
                            {% endif %}
                            <li class="{% if 'home' in selected %}selected{% endif %} w-36 p-1 mb-2"><a href="{% url "public:home" %}"><span class="mr-1">🏡</span><span>Home</span></a></li>
                            {% for stream in streams %}
                                <li class="{% if stream.slug in selected %}selected{% endif %} w-36 p-1 mb-2"><a href="{% url "public:stream" stream.slug %}"><span class="mr-1">{{ stream.icon }}</span><span>{{ stream.name }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </nav>
                {% endblock %}
            <div class="flex-col md:w-11/12 md:flex">
                {% block content_before %}{% endblock %}
                <div id="main-container" class="flex-col md:flex">
                    {% block content %}
                        <main id="main" class="main md:w-9/12 max-w-prose md:order-first p-2">
                            {% block breadcrumbs_block %}
                                <nav id="breadcrumbs" class="breadcrumbs pb-2 mb-2">
                                    {% block breadcrumbs %}{% endblock %}
                                </nav>
                            {% endblock %}
                            {% block main %}{% endblock %}
                        </main>
                        {% block meta_section %}
                        <section id="meta" class="meta order-first md:w-3/12 p-2">
                            {% block meta %}{% endblock %}
                        </section>
                        {% endblock %}
                    {% endblock  %}
                </div>
                {% block content_after %}
                {% endblock %}
            </div>
            {% endblock %}
        </div>
        <footer class="w-full">
            {{ request.settings.footer_snippet|safe }}
        </footer>
    </div>
</body>
</html>