apps/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.utils import text
from plugins import pool

from . import views

urlpatterns = [
    path("a/", include("entry.urls")),
    path("a/", include("post.urls", namespace="post")),
    path("a/", include("files.admin_urls")),
    path("a/", include("trips.urls")),
    path("a/", include("plugins.urls")),
    path("a/wordpress/", include("wordpress.urls", namespace="wordpress")),
    path("a/", include("indieweb.urls", namespace="indieweb")),
    path("files/", include("files.urls")),
    path("", include("feeds.urls", namespace="feeds")),
    path("webmention/", include("webmention.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("favicon.ico", views.favicon),
]

# Include any plugin urls after core urls.
plugin_urls = [path("", include(plugin_urls)) for plugin_urls in pool.plugin_pool.urls()]
urlpatterns.extend(plugin_urls)

plugin_admin_urls = [
    path(f"a/plugins/{text.slugify(plugin.name)}/", include(plugin.admin_urls))
    for plugin in pool.plugin_pool.enabled_plugins()
    if plugin.admin_urls
]
urlpatterns.extend(plugin_admin_urls)

# Public urls are last so "slug-like" urls in plugins are not matched to the stream-list view.
urlpatterns.append(
    path("", include("public.urls", namespace="public")),
)


handler404 = views.handle404

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

apps/wordpress/urls.py
from django.urls import path

from . import views

app_name = "wordpress"

urlpatterns = [
    path("upload/", views.TWordpressCreate.as_view(), name="t_wordpress_create"),
    path("upload/<int:pk>/categories", views.category_mappings, name="t_category_mapping"),
    path(
        "upload/<int:pk>/postkinds",
        views.post_kind_mappings,
        name="t_post_kind_mapping",
    ),
    path(
        "upload/<int:pk>/attachments",
        views.t_wordpress_attachments,
        name="t_wordpress_attachment_list",
    ),
    path(
        "attachment/<uuid:uuid>/import",
        views.import_attachment,
        name="import_attachment",
    ),
    path(
        "upload/<int:pk>/import_posts",
        views.import_posts,
        name="import_posts",
    ),
    path("", views.TWordpressListView.as_view(), name="t_wordpress_list"),
]

apps/wordpress/forms.py
from typing import List
from urllib.parse import urlparse

from bs4 import BeautifulSoup
from django import forms
from django.db import transaction
from post.models import TPost
from streams.forms import StreamModelChoiceField
from streams.models import MStream

from .extract import extract_categories, extract_post_format, extract_post_kind
from .models import (
    TCategory,
    TPostFormat,
    TPostKind,
    TWordpress,
    TWordpressAttachment,
    TWordpressPost,
)


class WordpressUploadForm(forms.ModelForm):
    class Meta:
        model = TWordpress
        fields = ["export_file"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.t_categories: List[TCategory] = []
        self.t_post_formats: List[TPostFormat] = []
        self.t_post_kinds: List[TPostKind] = []
        self.t_attachments: List[TWordpressAttachment] = []
        self.t_posts: List[TWordpressPost] = []

    def clean_export_file(self):
        if self.cleaned_data["export_file"].content_type not in [
            "application/xml",
            "text/xml",
        ]:
            raise forms.ValidationError("File must be XML")
        return self.cleaned_data["export_file"]

    def clean(self):
        # Extract basic link / base url and so forth information
        # prepare base transaction records for the import
        soup = BeautifulSoup(self.cleaned_data["export_file"], "xml")
        self.instance.link = soup.find("link").text
        self.instance.base_site_url = soup.find("wp:base_site_url").text
        self.instance.base_blog_url = soup.find("wp:base_blog_url").text

        self.t_categories.extend(
            [TCategory(name=name, nice_name=nice_name) for name, nice_name in extract_categories(soup)]
        )
        self.t_post_formats.extend(
            [TPostFormat(name=name, nice_name=nice_name) for name, nice_name in extract_post_format(soup)]
        )
        self.t_post_kinds.extend(
            [TPostKind(name=name, nice_name=nice_name) for name, nice_name in extract_post_kind(soup)]
        )
        self._extract_attachments(soup)
        self._extract_posts(soup)

    def _extract_attachments(self, soup):
        attachments = soup.find_all("wp:post_type", text="attachment")
        self.t_attachments.extend(
            [
                TWordpressAttachment(
                    guid=attachment.parent.find("guid").text,
                    link=attachment.parent.find("link").text,
                )
                for attachment in attachments
            ]
        )

    def _extract_posts(self, soup):
        posts = soup.find_all("wp:post_type", text="post")
        self.t_posts.extend(
            [
                TWordpressPost(
                    guid=post.parent.find("guid").text,
                    path=urlparse(post.parent.find("link").text).path,
                )
                for post in posts
            ]
        )

    @transaction.atomic
    def save(self, commit=True):
        instance = super().save(commit)

        for t_category in self.t_categories:
            t_category.t_wordpress = instance
        TCategory.objects.bulk_create(self.t_categories)

        for t_post_kind in self.t_post_kinds:
            t_post_kind.t_wordpress = instance
        TPostKind.objects.bulk_create(self.t_post_kinds)

        for t_post_format in self.t_post_formats:
            t_post_format.t_wordpress = instance
        TPostFormat.objects.bulk_create(self.t_post_formats)

        for t_attachment in self.t_attachments:
            t_attachment.t_wordpress = instance
        TWordpressAttachment.objects.bulk_create(self.t_attachments)

        for t_post in self.t_posts:
            t_post.t_wordpress = instance
        TWordpressPost.objects.bulk_create(self.t_posts)

        return instance


class TCategoryModelForm(forms.ModelForm):

    t_stream = StreamModelChoiceField(MStream.objects, label="", empty_label="Skip", required=False)

    class Meta:
        model = TCategory
        fields = ("m_stream",)


class TPostKindModelForm(forms.ModelForm):
    class Meta:
        model = TPostKind
        fields = ("m_post_kind",)


class ImportTWordpressPostForm(forms.ModelForm):
    class Meta:
        model = TWordpressPost
        fields = ("t_post",)

    def __init__(self, *args, soup: BeautifulSoup, **kwargs):
        super().__init__(*args, **kwargs)
        self.soup = soup
        self.item = None

    def prepare_data(self):
        self.t_post = self.instance.t_post or TPost()

        # loop through item xml and prepare objects

apps/wordpress/views.py
import logging
from pathlib import Path

from bs4 import BeautifulSoup
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.defaultfilters import linebreaks_filter, safe
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView
from entry.forms import (
    CreateArticleForm,
    CreateBookmarkForm,
    CreateCheckinForm,
    CreateReplyForm,
    CreateStatusForm,
    TCheckinModelForm,
    TLocationModelForm,
    TSyndicationModelForm,
    UpdateArticleForm,
    UpdateBookmarkForm,
    UpdateCheckinForm,
    UpdateReplyForm,
    UpdateStatusForm,
)
from entry.models import TCheckin, TLocation
from files.forms import MediaUploadForm
from files.images import bytes_as_upload_image
from indieweb.application.location import location_to_pointfield_input
from indieweb.utils import download_image, render_attachment
from turbo_response import TurboFrame, redirect_303

from . import extract
from .forms import TCategoryModelForm, TPostKindModelForm, WordpressUploadForm
from .models import (
    TCategory,
    TPostKind,
    TWordpress,
    TWordpressAttachment,
    TWordpressPost,
)

logger = logging.getLogger(__name__)


@method_decorator(login_required, name="dispatch")
class TWordpressListView(ListView):

    model = TWordpress
    allow_empty = False

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            return redirect_303("wordpress:t_wordpress_create")


@method_decorator(login_required, name="dispatch")
class TWordpressCreate(CreateView):
    form_class = WordpressUploadForm
    template_name = "wordpress/wordpress_create.html"

    def get_success_url(self):
        return reverse("wordpress:t_category_mapping", args=[self.object.pk])


@login_required
def category_mappings(request, pk):
    t_wordpress = get_object_or_404(TWordpress, pk=pk)
    TCategoryModelFormSet = forms.inlineformset_factory(TWordpress, TCategory, form=TCategoryModelForm, extra=0)
    formset = TCategoryModelFormSet(request.POST or None, instance=t_wordpress)
    if request.method == "POST" and formset.is_valid():
        formset.save()
        messages.success(request, "Updated Category Mapping")
        return redirect_303("wordpress:t_wordpress_list")
    context = {
        "t_wordpress": t_wordpress,
        "formset": formset,
    }
    return render(request, "wordpress/tcategory_mapping.html", context=context)


@login_required
def post_kind_mappings(request, pk):
    t_wordpress = get_object_or_404(TWordpress, pk=pk)
    TPostKindModelFormSet = forms.inlineformset_factory(TWordpress, TPostKind, form=TPostKindModelForm, extra=0)
    formset = TPostKindModelFormSet(request.POST or None, instance=t_wordpress)
    if request.method == "POST" and formset.is_valid():
        formset.save()
        messages.success(request, "Updated Post Kind Mapping")
        return redirect_303("wordpress:t_wordpress_list")
    context = {
        "t_wordpress": t_wordpress,
        "formset": formset,
    }
    return render(request, "wordpress/tpostkind_mapping.html", context=context)


@login_required
def t_wordpress_attachments(request, pk):
    t_wordpress = get_object_or_404(TWordpress, pk=pk)
    context = {
        "t_wordpress": t_wordpress,
        "attachment_count": t_wordpress.ref_t_wordpress_attachment.count(),
        "imported": t_wordpress.ref_t_wordpress_attachment.filter(t_file__isnull=False).select_related("t_file"),
        "object_list": t_wordpress.ref_t_wordpress_attachment.filter(t_file__isnull=True),
    }
    return render(request, "wordpress/twordpressattachment_list.html", context=context)


@login_required
def import_attachment(request, uuid):
    t_attachment = get_object_or_404(TWordpressAttachment, uuid=uuid)
    if t_attachment.t_file:
        return JsonResponse(status=400, data={"error": "already_imported"})
    data_image = download_image(t_attachment.guid)
    filename = Path(t_attachment.guid).name
    upload_image, _, _ = bytes_as_upload_image(data_image.image_data, data_image.mime_type, filename)
    form = MediaUploadForm(files={"file": upload_image})
    if form.is_valid():
        t_file = form.save()
        t_attachment.t_file = t_file
        t_attachment.save()
        response = HttpResponse(status=201)
        response["Location"] = request.build_absolute_uri(t_file.get_absolute_url())
    return (
        TurboFrame(uuid)
        .template(
            "wordpress/_attachment.html",
            context={
                "t_wordpress_attachment": t_attachment,
                "img_src": t_attachment.t_file.get_absolute_url(),
            },
        )
        .response(request)
    )


@login_required
def import_posts(request, pk):
    t_wordpress = get_object_or_404(TWordpress, pk=pk)
    context = {
        "t_wordpress": t_wordpress,
        "unimported_attachments": t_wordpress.ref_t_wordpress_attachment.filter(t_file__isnull=True).exists(),
        "category_map": t_wordpress.ref_t_category.filter(m_stream__isnull=False).exists(),
        "postkind_map": t_wordpress.ref_t_post_kind.filter(m_post_kind__isnull=False).exists(),
    }
    if request.method == "POST":
        soup = BeautifulSoup(t_wordpress.export_file.read(), "xml")

        for t_post in t_wordpress.ref_t_wordpress_post.all():
            import_post(request, t_post, soup)
        messages.success(request, "Imported Posts 🎉")
    return render(request, "wordpress/import_posts.html", context=context)


def import_post(request, t_wordpress_post: TWordpressPost, soup: BeautifulSoup):  # noqa: C901  too complex (32)!

    guid = soup.find("guid", text=t_wordpress_post.guid)
    t_post = t_wordpress_post.t_post
    if t_post:
        t_entry = t_post.ref_t_entry
    else:
        t_entry = None

    if not guid:

        raise forms.ValidationError("Guid doesn't exist in export file")
    item = guid.parent
    logging.info("Processing %s", guid)
    named_forms = {}
    dt_published = extract.extract_published_date(item)
    categories = extract.extract_categories(item)
    form_data = {
        "p_name": item.find("title").text,
        "e_content": item.find("encoded").text,
        "m_post_status": "".join(extract.extract_post_status(item)),
        "dt_published": dt_published.isoformat() if dt_published else None,
        "streams": TCategory.objects.exclude(m_stream__isnull=True)
        .filter(nice_name__in=[nice_name for _, nice_name in categories])
        .values_list("m_stream_id", flat=True),
    }

    reply = extract.extract_in_reply_to(item)
    bookmark_of = extract.extract_bookmark(item)
    if reply:
        logging.info("Has reply")
        form_data.update(
            {
                "u_in_reply_to": reply.url,
                "title": reply.title,
                "author": reply.author.name if reply.author else "",
                "summary": reply.description,
            }
        )
    elif bookmark_of:
        logging.info("Has bookmark")
        form_data.update(
            {
                "u_bookmark_of": bookmark_of.url,
                "title": bookmark_of.title or bookmark_of.url,
                "author": bookmark_of.author.name if bookmark_of.author else "",
                "summary": bookmark_of.description,
            }
        )

    # Process related content
    location = extract.extract_location(item)
    checkin = extract.extract_checkin(item)
    syndication = extract.extract_syndication(item)
    if location:
        logging.info("Has location")
        location["point"] = location_to_pointfield_input(location["point"])
        try:
            t_location = t_entry.t_location
        except (TLocation.DoesNotExist, AttributeError):
            t_location = None

        named_forms["location"] = TLocationModelForm(data=location, instance=t_location)
    if checkin:
        logging.info("Has checkin")
        try:
            t_checkin = t_entry.t_checkin
        except (TCheckin.DoesNotExist, AttributeError):
            t_checkin = None
        named_forms["checkin"] = TCheckinModelForm(data=checkin, instance=t_checkin)
    if syndication:
        logging.info("Has syndication")
        for idx, syndication_url in enumerate(syndication):
            t_syndication = t_entry.t_syndication.filter(url=syndication_url).first() if t_entry else None
            named_forms[f"syndication_{idx}"] = TSyndicationModelForm(
                data={"url": syndication_url}, instance=t_syndication
            )

    # Rewrite any image links
    content = BeautifulSoup(form_data["e_content"], "html.parser")
    images = extract.extract_images(content, t_wordpress_post.t_wordpress.base_site_url)
    for image in images:
        image_url = image["src"].replace("-scaled", "").replace("https://micro.blog/photos/200/", "")
        image_attachment = (
            TWordpressAttachment.objects.filter(
                t_wordpress_id=t_wordpress_post.t_wordpress_id,
                guid__startswith=image_url,
            )
            .select_related("t_file")
            .first()
        )
        if image_attachment:
            tag = BeautifulSoup(render_attachment(request, image_attachment.t_file), "html.parser")
            if image.parent and image.parent.name == "a":
                image.parent.replace_with(tag)
            else:
                image.replace_with(tag)
        else:
            logger.info(
                "%s has no attachment is possibly a dead url t_wordpress_post.uuid=%s",
                image_url,
                t_wordpress_post.uuid,
            )
    form_data["e_content"] = str(content)

    # Append any attachments
    if t_wordpress_post.path != "/":

apps/templates/wordpress/_attachment.html
<a href="{{ img_src }}" class="mr-2"><img src="{{ img_src }}" width="100" height="100" loading="lazy"/></a>
<div class="flex-col">
    <div class="flex">
        {% if loading %}
            {% include "fragments/loading.html" with color="text-negroni-900" %}Importing...
        {% else %}
            {{ t_wordpress_attachment.t_file_id|yesno:"Imported,Pending" }}
        {% endif %}
    </div>
    <div class="help-text">
        {{ t_wordpress_attachment.guid|urlize}}
    </div>
</div>

apps/templates/wordpress/import_posts.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        {% include "fragments/messages.html" %}
    {% endif %}
    <h1 class="text-xl">Importing Posts</h1>
    <ul>
        {% if unimported_attachments %}
            <li>❌ Finish importing attachments.</li>
        {% else %}
            <li>✅ Attachments Imported</li>
        {% endif %}

        {% if category_map %}
            <li>✅ Categories Mapped</li>
        {% else %}
            <li>❌ Category mapping isn't set.</li>
        {% endif %}

        {% if postkind_map %}
            <li>✅ Postkinds Mapped</li>
        {% else %}
            <li>❌ Postkind mapping isn't set.</li>
        {% endif %}
    </ul>
    <form method="post">
        {% csrf_token %}
        <button class="rounded mt-2 text-white bg-malachite-800 border-malachite-900 px-3 py-1 border" type="submit" data-turbo="false">Import Posts</button>
    </form>
{% endblock %}

apps/templates/wordpress/tcategory_mapping.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        {% include "fragments/messages.html" %}
    {% endif %}
    <h1 class="text-xl">Category Mapping</h1>
    <p class="mt-2">Select the Streams that each wordpress category imported into.</p>
    <p>If the existing streams don't map well you can <a href="{% url 'admin:streams_mstream_changelist' %}" class="underline">create a new stream</a>.</p>
    <form method="post" class="flex-col mt-2 text-left">
        {% csrf_token %}
        {{ formset.management_form }}
        <table>
            <tr>
                <th class="align-top">Category</th>
                <th class="pl-2">Stream
                    <p class="block help-text" style="font-weight: normal;">Categories without a stream selected will not be imported.</p>
                </th>
            </tr>
            {% for form in formset.forms %}
                <tr class="p-2">
                    <td class="pr-2">{{ form.instance.name }}{{ form.id }}</td>
                    <td class="p-2">{{ form.m_stream }}{{ form.errors.m_stream }}</td>
                </tr>
                {% if form.non_field_errors %}
                    <tr>
                        <td colspan="2">{{ form.non_field_errors }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
        <button class="rounded mt-2 text-white bg-malachite-800 border-malachite-900 px-3 py-1 border" name="m_post_status" type="submit" data-turbo="false">Save Mapping</button>
    </form>
{% endblock %}

apps/templates/wordpress/tpostkind_mapping.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        {% include "fragments/messages.html" %}
    {% endif %}
    <h1 class="text-xl">Post Kind Mapping</h1>
    <p class="mt-2">Select the post kind that each post kind should imported into.</p>
    <form method="post" class="flex-col mt-2 text-left">
        {% csrf_token %}
        {{ formset.management_form }}
        <table>
            <tr>
                <th class="align-top">Wordpress Post Kind</th>
                <th class="pl-2">Post Kind
                    <p class="block help-text" style="font-weight: normal;">Wordpress Post Kinds without a post kind selected will be imported as an Article.</p>
                </th>
            </tr>
            {% for form in formset.forms %}
                <tr class="p-2">
                    <td class="pr-2">{{ form.instance.name }}{{ form.id }}</td>
                    <td class="p-2">{{ form.m_post_kind }}{{ form.errors.m_post_kind }}</td>
                </tr>
                {% if form.non_field_errors %}
                    <tr>
                        <td colspan="2">{{ form.non_field_errors }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
        <button class="rounded mt-2 text-white bg-malachite-800 border-malachite-900 px-3 py-1 border" name="m_post_status" type="submit" data-turbo="false">Save Mapping</button>
    </form>
{% endblock %}

apps/templates/wordpress/twordpress_list.html
{% extends "base.html" %}
{% load utils %}
{% block content %}
    {% if messages %}
        {% include "fragments/messages.html" %}
    {% endif %}
    <h1 class="text-xl">Import from Wordpress</h1>
    <ul>
        {% for t_wordpress in object_list %}
            <li class="flex mt-2">
            <div class="flex-col">
                <span>{{ t_wordpress }}</span>
                <span class="block help-text">{{ t_wordpress.link|domain }}</span>
            </div>
            <a href="{% url 'wordpress:t_category_mapping' t_wordpress.pk %}" class="mr-2">Category Mapping</a>
            <a href="{% url 'wordpress:t_post_kind_mapping' t_wordpress.pk %}" class="mr-2">Post Kind Mapping</a>
            <a href="{% url 'wordpress:t_wordpress_attachment_list' t_wordpress.pk %}" class="mr-2">Import Attachments</a>
            <a>Import Posts</a>
            </li>
        {% endfor %}
     </ul>
{% endblock %}

apps/templates/wordpress/twordpressattachment_list.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        {% include "fragments/messages.html" %}
    {% endif %}
    <h1 class="text-xl">Importing Attachments...</h1>
    <p>Leave this page open while Tanzawa imports your attachments.</p>
    <ul>
        {% for t_wordpress_attachment in object_list reversed %}
            <li class="flex mt-2">
                <turbo-frame id="{{ t_wordpress_attachment.uuid }}" class="flex" src="{% url 'wordpress:import_attachment' t_wordpress_attachment.uuid %}">
                    {% include "wordpress/_attachment.html" with img_src=t_wordpress_attachment.guid loading="true" %}
                </turbo-frame>
            </li>
        {% endfor %}
        {% for t_wordpress_attachment in imported reversed %}
            <li class="flex mt-2">
                <turbo-frame loading="lazy" class="flex">
                    {% include "wordpress/_attachment.html" with img_src=t_wordpress_attachment.t_file.get_absolute_url %}
                </turbo-frame>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

apps/templates/wordpress/wordpress_create.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-xl">Import Wordpress Posts</h1>
    <div class="max-w-prose mt-2">
        <p>Using this Wordpress import tool you can automatically import your posts from Wordpress into Tanzawa.
            After uploading your export file, Tanzawa will ask how to map between categories and streams.
        </p>
        <p class="mt-2">Once you're happy with import settings, Tanzawa will import all posts and attachments from your Wordpress site.</p>
    </div>
    <form method="post" enctype="multipart/form-data" class="flex-col">
        {% csrf_token %}
        {{ form.errors }}
        <div class="mt-2">
            {{ form.export_file }}
        </div>

        <button class="rounded mt-2 text-white bg-malachite-800 border-malachite-900 px-3 py-1 border" name="m_post_status" type="submit" data-turbo="false">Upload</button>
    </form>
{% endblock %}